### ISSUE TITLE
Doesn't handle redirects

### ISSUE THREAD

**Issue by Daniel15** [pruvisto/debirdify#4]
I get this error:
> We found the following Fediverse IDs in [your](https://twitter.com/Daniel15) Twitter profile:
> 
>     [dan@d.sb](https://d.sb/@dan) ❌
>     This account does not seem to exist.

https://d.sb/.well-known/webfinger?resource=acct:dan@d.sb works, but it redirects to https://toot.d.sb/.well-known/webfinger?resource=acct:dan@d.sb. This is a valid configuration - see the `WEB_DOMAIN` section of https://docs.joinmastodon.org/admin/config/

Your code needs to follow the redirect.

**Comment by pruvisto** [comment]
This is fixed as of b0ef5f3ca70d2dbd30b29b4dae1b5bae6a9710ea, but the profile link that is being generated is broken since it is generated as https://d.sb/@dan, which is a 404. The easiest way to fix this would be for you to install a redirect to https://toot.d.sb/@dan on your server.

I don't think I can solve this robustly in the scraper without doing a webfinger query for every single ID encountered, which does not scale. One could try to cache these things, of course, but I'm not sure I want to do that.

**Comment by Daniel15** [comment]
Thanks @pruvisto! I've just configured the redirect.

**Comment by pruvisto** [comment]
I just implemented a more robust way to do this and it seems to work. Note however that your domain d.sb does not serve a host-meta file, which I think it should.

**Comment by Daniel15** [comment]
Thank you :)

> Note however that your domain d.sb does not serve a host-meta file, which I think it should.

What is a host-meta file?

**Comment by pruvisto** [comment]
See here: https://github.com/felx/mastodon-documentation/blob/master/Running-Mastodon/Serving_a_different_domain.md

(especially the "Webfinger" section)

**Comment by Daniel15** [comment]
@pruvisto  Interesting! This isn't mentioned in the modern Mastodon docs at all: https://docs.joinmastodon.org/admin/config/. The only thing they say to redirect is `/.well-known/webfinger`. In my case I also redirected `/.well-known/nodeinfo` and `/@dan` too: https://github.com/Daniel15/Website/commit/149fdd3c2b4ecf3bb9d99c22eb5919bbe4d6834b

**Comment by pruvisto** [comment]
Honestly I have no idea what the correct thing to do here is. I only know about host-meta because somebody else pointed it out to me in a Github issue. I am very sure I know much less about Mastodon (or ActivityPub) than you do.
